-- Nordly regional seed data
-- Safe to run multiple times.

insert into public.currencies (code, name, symbol, minor_unit, is_active)
values
  ('AED', 'UAE Dirham', 'AED', 2, true),
  ('ARS', 'Argentine Peso', 'ARS', 2, true),
  ('AUD', 'Australian Dollar', 'A$', 2, true),
  ('BGN', 'Bulgarian Lev', 'BGN', 2, true),
  ('BRL', 'Brazilian Real', 'R$', 2, true),
  ('CAD', 'Canadian Dollar', 'C$', 2, true),
  ('CHF', 'Swiss Franc', 'CHF', 2, true),
  ('CLP', 'Chilean Peso', 'CLP', 0, true),
  ('CNY', 'Chinese Yuan', 'CNY', 2, true),
  ('COP', 'Colombian Peso', 'COP', 2, true),
  ('CZK', 'Czech Koruna', 'CZK', 2, true),
  ('DKK', 'Danish Krone', 'kr', 2, true),
  ('EGP', 'Egyptian Pound', 'EGP', 2, true),
  ('EUR', 'Euro', 'EUR', 2, true),
  ('GBP', 'Pound Sterling', 'GBP', 2, true),
  ('HKD', 'Hong Kong Dollar', 'HK$', 2, true),
  ('HUF', 'Hungarian Forint', 'HUF', 2, true),
  ('IDR', 'Indonesian Rupiah', 'IDR', 2, true),
  ('ILS', 'Israeli New Shekel', 'ILS', 2, true),
  ('INR', 'Indian Rupee', 'INR', 2, true),
  ('ISK', 'Icelandic Krona', 'ISK', 0, true),
  ('JPY', 'Japanese Yen', 'JPY', 0, true),
  ('KRW', 'South Korean Won', 'KRW', 0, true),
  ('MAD', 'Moroccan Dirham', 'MAD', 2, true),
  ('MXN', 'Mexican Peso', 'MX$', 2, true),
  ('MYR', 'Malaysian Ringgit', 'MYR', 2, true),
  ('NOK', 'Norwegian Krone', 'kr', 2, true),
  ('NZD', 'New Zealand Dollar', 'NZ$', 2, true),
  ('PEN', 'Peruvian Sol', 'PEN', 2, true),
  ('PHP', 'Philippine Peso', 'PHP', 2, true),
  ('PLN', 'Polish Zloty', 'PLN', 2, true),
  ('QAR', 'Qatari Riyal', 'QAR', 2, true),
  ('RON', 'Romanian Leu', 'RON', 2, true),
  ('RSD', 'Serbian Dinar', 'RSD', 2, true),
  ('SAR', 'Saudi Riyal', 'SAR', 2, true),
  ('SEK', 'Swedish Krona', 'kr', 2, true),
  ('SGD', 'Singapore Dollar', 'S$', 2, true),
  ('THB', 'Thai Baht', 'THB', 2, true),
  ('TRY', 'Turkish Lira', 'TRY', 2, true),
  ('UAH', 'Ukrainian Hryvnia', 'UAH', 2, true),
  ('USD', 'US Dollar', '$', 2, true),
  ('VND', 'Vietnamese Dong', 'VND', 0, true),
  ('ZAR', 'South African Rand', 'ZAR', 2, true)
on conflict (code) do update
set
  name = excluded.name,
  symbol = excluded.symbol,
  minor_unit = excluded.minor_unit,
  is_active = excluded.is_active;

insert into public.countries (code, name, currency_code, region, is_active)
values
  ('AE', 'United Arab Emirates', 'AED', 'Middle East', true),
  ('AR', 'Argentina', 'ARS', 'South America', true),
  ('AT', 'Austria', 'EUR', 'Europe', true),
  ('AU', 'Australia', 'AUD', 'Oceania', true),
  ('BE', 'Belgium', 'EUR', 'Europe', true),
  ('BG', 'Bulgaria', 'BGN', 'Europe', true),
  ('BR', 'Brazil', 'BRL', 'South America', true),
  ('CA', 'Canada', 'CAD', 'North America', true),
  ('CH', 'Switzerland', 'CHF', 'Europe', true),
  ('CL', 'Chile', 'CLP', 'South America', true),
  ('CN', 'China', 'CNY', 'Asia', true),
  ('CO', 'Colombia', 'COP', 'South America', true),
  ('CZ', 'Czech Republic', 'CZK', 'Europe', true),
  ('DE', 'Germany', 'EUR', 'Europe', true),
  ('DK', 'Denmark', 'DKK', 'Europe', true),
  ('EG', 'Egypt', 'EGP', 'Africa', true),
  ('ES', 'Spain', 'EUR', 'Europe', true),
  ('FI', 'Finland', 'EUR', 'Europe', true),
  ('FR', 'France', 'EUR', 'Europe', true),
  ('GB', 'United Kingdom', 'GBP', 'Europe', true),
  ('GR', 'Greece', 'EUR', 'Europe', true),
  ('HK', 'Hong Kong', 'HKD', 'Asia', true),
  ('HR', 'Croatia', 'EUR', 'Europe', true),
  ('HU', 'Hungary', 'HUF', 'Europe', true),
  ('ID', 'Indonesia', 'IDR', 'Asia', true),
  ('IE', 'Ireland', 'EUR', 'Europe', true),
  ('IL', 'Israel', 'ILS', 'Middle East', true),
  ('IN', 'India', 'INR', 'Asia', true),
  ('IS', 'Iceland', 'ISK', 'Europe', true),
  ('IT', 'Italy', 'EUR', 'Europe', true),
  ('JP', 'Japan', 'JPY', 'Asia', true),
  ('KR', 'South Korea', 'KRW', 'Asia', true),
  ('LT', 'Lithuania', 'EUR', 'Europe', true),
  ('LU', 'Luxembourg', 'EUR', 'Europe', true),
  ('LV', 'Latvia', 'EUR', 'Europe', true),
  ('MA', 'Morocco', 'MAD', 'Africa', true),
  ('MX', 'Mexico', 'MXN', 'North America', true),
  ('MY', 'Malaysia', 'MYR', 'Asia', true),
  ('NL', 'Netherlands', 'EUR', 'Europe', true),
  ('NO', 'Norway', 'NOK', 'Europe', true),
  ('NZ', 'New Zealand', 'NZD', 'Oceania', true),
  ('PE', 'Peru', 'PEN', 'South America', true),
  ('PH', 'Philippines', 'PHP', 'Asia', true),
  ('PL', 'Poland', 'PLN', 'Europe', true),
  ('PT', 'Portugal', 'EUR', 'Europe', true),
  ('QA', 'Qatar', 'QAR', 'Middle East', true),
  ('RO', 'Romania', 'RON', 'Europe', true),
  ('RS', 'Serbia', 'RSD', 'Europe', true),
  ('SA', 'Saudi Arabia', 'SAR', 'Middle East', true),
  ('SE', 'Sweden', 'SEK', 'Europe', true),
  ('SG', 'Singapore', 'SGD', 'Asia', true),
  ('SI', 'Slovenia', 'EUR', 'Europe', true),
  ('SK', 'Slovakia', 'EUR', 'Europe', true),
  ('TH', 'Thailand', 'THB', 'Asia', true),
  ('TR', 'Turkey', 'TRY', 'Europe', true),
  ('UA', 'Ukraine', 'UAH', 'Europe', true),
  ('US', 'United States', 'USD', 'North America', true),
  ('VN', 'Vietnam', 'VND', 'Asia', true),
  ('ZA', 'South Africa', 'ZAR', 'Africa', true)
on conflict (code) do update
set
  name = excluded.name,
  currency_code = excluded.currency_code,
  region = excluded.region,
  is_active = excluded.is_active;
